//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM_SystemEntities : DbContext
    {
        public CRM_SystemEntities()
            : base("name=CRM_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Mpr_Admin_ButtonRole> Mpr_Admin_ButtonRole { get; set; }
        public DbSet<Mpr_Admin_Menu> Mpr_Admin_Menu { get; set; }
        public DbSet<Mpr_Admin_Role> Mpr_Admin_Role { get; set; }
        public DbSet<Mpr_Basic_Params> Mpr_Basic_Params { get; set; }
        public DbSet<Mpr_Customer> Mpr_Customer { get; set; }
        public DbSet<Mpr_Customer_Log> Mpr_Customer_Log { get; set; }
        public DbSet<Mpr_InterfaceCall_Log> Mpr_InterfaceCall_Log { get; set; }
        public DbSet<Mpr_Material_Type> Mpr_Material_Type { get; set; }
        public DbSet<Mpr_Organization> Mpr_Organization { get; set; }
        public DbSet<Sys_Admin> Sys_Admin { get; set; }
        public DbSet<Sys_Error_log> Sys_Error_log { get; set; }
        public DbSet<Sys_Role> Sys_Role { get; set; }
        public DbSet<Mpr_Material> Mpr_Material { get; set; }
        public DbSet<View_Phone_WareHouse> View_Phone_WareHouse { get; set; }
        public DbSet<View_User_Phone> View_User_Phone { get; set; }
    }
}
