//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpr_Material_Type
    {
        public string ID { get; set; }
        public string TypeName { get; set; }
        public int Sort { get; set; }
        public System.DateTime AddTime { get; set; }
        public int AddUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
