//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpr_Customer
    {
        public string ID { get; set; }
        public string ID_Card { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int Sex { get; set; }
        public string Birthday { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string QQ { get; set; }
        public string WeChat { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<int> SharesAge { get; set; }
        public string Company { get; set; }
        public string InvestmentVariety { get; set; }
        public Nullable<decimal> AvailableMoney { get; set; }
        public Nullable<int> InvestmentAdviser { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string Sale { get; set; }
        public string SaleDep { get; set; }
        public Nullable<int> SaleDirectorID { get; set; }
        public string SaleDirector { get; set; }
        public Nullable<int> SaleManagerID { get; set; }
        public string SaleManager { get; set; }
        public Nullable<int> SaleChiefID { get; set; }
        public string SaleChief { get; set; }
        public Nullable<int> AddUser { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> ChangeUser { get; set; }
        public Nullable<System.DateTime> Changetime { get; set; }
    }
}
