//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpr_Admin_ButtonRole
    {
        public int ID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string Operation { get; set; }
        public string ButtonName { get; set; }
        public Nullable<int> Roletype { get; set; }
        public string OnlyStr { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    }
}
