//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpr_Admin_Menu
    {
        public int ID { get; set; }
        public string RightUrl { get; set; }
        public string RightName { get; set; }
        public string Ename { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> RightParent { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public Nullable<int> IsButton { get; set; }
    }
}
