//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Admin
    {
        public int ID { get; set; }
        public string UName { get; set; }
        public string TrueName { get; set; }
        public string LoginPwd { get; set; }
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> AdminType { get; set; }
        public Nullable<int> FirstID { get; set; }
    }
}
