//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role
    {
        public string ID { get; set; }
        public string ROLENAME { get; set; }
        public string Ename { get; set; }
        public string ROLEVALUE { get; set; }
        public string ButtonRole { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> ShowLv { get; set; }
    }
}
