//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Phone_WareHouse
    {
        public string ID { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<int> Status { get; set; }
        public string TaskID { get; set; }
        public string PhoneID { get; set; }
        public Nullable<System.DateTime> FirstTasktime { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> Adduser { get; set; }
        public string Tag { get; set; }
        public string Mac { get; set; }
        public string RegistrationID { get; set; }
        public string AbnormalAlert { get; set; }
        public Nullable<int> User_Phone_Status { get; set; }
        public Nullable<int> LinkCount { get; set; }
        public string TaskDes { get; set; }
        public Nullable<int> TaskType { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public string TaskData { get; set; }
    }
}
