//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User_Phone
    {
        public string ID { get; set; }
        public string Tag { get; set; }
        public string Mac { get; set; }
        public string RegistrationID { get; set; }
        public Nullable<int> Status { get; set; }
        public string AbnormalAlert { get; set; }
        public int LinkCount { get; set; }
        public System.DateTime Addtime { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string UName { get; set; }
        public string TrueName { get; set; }
        public string RoleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string AddUserIP { get; set; }
    }
}
